from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

required_columns = {
    "genai_use_case_register.csv": [
        "use_case_id", "use_case_name", "genai_type", "agentic_ai_flag",
        "business_function", "user_group", "data_sensitivity",
        "external_tool_access", "memory_enabled", "customer_facing",
        "vendor_involved", "risk_tier", "approval_status"
    ],
    "prompt_test_cases.csv": [
        "test_id", "use_case_id", "prompt_category", "prompt_text",
        "expected_behavior", "actual_behavior", "risk_detected",
        "test_result", "reviewer_notes"
    ],
    "agent_tool_calls.csv": [
        "event_id", "use_case_id", "agent_action", "tool_accessed",
        "data_accessed", "approval_required", "approval_status",
        "action_completed", "risk_flag", "escalation_required", "timestamp"
    ],
    "pii_leakage_tests.csv": [
        "test_id", "use_case_id", "pii_type", "input_contains_pii",
        "output_contains_pii", "masking_applied", "leakage_detected",
        "severity", "remediation_action"
    ],
    "hallucination_eval_log.csv": [
        "eval_id", "use_case_id", "question", "source_available",
        "response_supported_by_source", "hallucination_detected",
        "severity", "human_review_required", "notes"
    ],
    "guardrail_test_results.csv": [
        "test_id", "use_case_id", "guardrail_name", "risk_category",
        "test_description", "expected_result", "actual_result",
        "pass_fail", "severity", "remediation_required"
    ],
    "human_escalation_log.csv": [
        "escalation_id", "use_case_id", "escalation_trigger",
        "user_request_type", "severity", "escalated_to", "decision",
        "resolution_time", "final_status"
    ],
    "genai_risk_register.csv": [
        "risk_id", "use_case_id", "risk_category", "risk_description",
        "inherent_risk", "guardrails_in_place", "residual_risk",
        "owner", "treatment_plan", "status"
    ],
    "genai_monitoring_plan.csv": [
        "use_case_id", "monitoring_metric", "threshold", "owner",
        "monitoring_frequency", "alert_trigger", "escalation_path", "status"
    ],
    "genai_control_library.csv": [
        "control_id", "guardrail_name", "risk_category", "control_objective",
        "control_type", "evidence_required", "owner", "test_frequency"
    ],
    "control_effectiveness_score.csv": [
        "control_id", "guardrail_name", "risk_category", "design_effectiveness",
        "operating_effectiveness", "last_test_date", "sample_size", "failures",
        "control_effectiveness_score", "rating", "remediation_status"
    ],
    "red_team_findings.csv": [
        "finding_id", "use_case_id", "attack_type", "finding_summary",
        "severity", "status", "owner", "remediation", "retest_required", "due_date"
    ],
    "genai_incident_log.csv": [
        "incident_id", "use_case_id", "incident_type", "severity", "detected_by",
        "containment_action", "root_cause", "customer_impact", "status", "closure_evidence"
    ],
    "residual_risk_decisions.csv": [
        "decision_id", "use_case_id", "risk_id", "residual_risk", "decision",
        "approver_role", "conditions", "review_date", "expiry_date"
    ],
}

risk_levels = {"Low", "Medium", "High", "Critical"}
valid_yes_no = {"Yes", "No", "Partial", "Restricted", "Not applicable"}
forbidden_readme_terms = [
    "portfolio",
    "student",
    "school project",
    "beginner",
    "chatgpt",
    "openai",
    "ai-generated",
    "generated by ai",
]

def main():
    frames = {}

    for filename, columns in required_columns.items():
        path = DATA / filename
        if not path.exists():
            raise FileNotFoundError(f"Missing required data file: {filename}")

        df = pd.read_csv(path)
        frames[filename] = df

        missing = set(columns) - set(df.columns)
        if missing:
            raise ValueError(f"{filename} missing columns: {sorted(missing)}")

        if df.empty:
            raise ValueError(f"{filename} is empty")

    use_case_ids = set(frames["genai_use_case_register.csv"]["use_case_id"])
    risk_ids = set(frames["genai_risk_register.csv"]["risk_id"])
    control_ids = set(frames["genai_control_library.csv"]["control_id"])
    guardrail_names = set(frames["genai_control_library.csv"]["guardrail_name"])

    files_with_use_case_id = [
        "prompt_test_cases.csv",
        "agent_tool_calls.csv",
        "pii_leakage_tests.csv",
        "hallucination_eval_log.csv",
        "guardrail_test_results.csv",
        "human_escalation_log.csv",
        "genai_risk_register.csv",
        "genai_monitoring_plan.csv",
        "red_team_findings.csv",
        "genai_incident_log.csv",
        "residual_risk_decisions.csv",
    ]

    for filename in files_with_use_case_id:
        unknown = set(frames[filename]["use_case_id"]) - use_case_ids
        if unknown:
            raise ValueError(f"{filename} contains unknown use_case_id values: {sorted(unknown)}")

    unknown_risks = set(frames["residual_risk_decisions.csv"]["risk_id"]) - risk_ids
    if unknown_risks:
        raise ValueError(f"residual_risk_decisions.csv contains unknown risk_id values: {sorted(unknown_risks)}")

    unknown_controls = set(frames["control_effectiveness_score.csv"]["control_id"]) - control_ids
    if unknown_controls:
        raise ValueError(f"control_effectiveness_score.csv contains unknown control_id values: {sorted(unknown_controls)}")

    unknown_guardrails = set(frames["guardrail_test_results.csv"]["guardrail_name"]) - guardrail_names
    if unknown_guardrails:
        raise ValueError(f"guardrail_test_results.csv contains unknown guardrail_name values: {sorted(unknown_guardrails)}")

    invalid_tiers = set(frames["genai_use_case_register.csv"]["risk_tier"]) - risk_levels
    if invalid_tiers:
        raise ValueError(f"Invalid risk_tier values: {sorted(invalid_tiers)}")

    invalid_inherent = set(frames["genai_risk_register.csv"]["inherent_risk"]) - risk_levels
    invalid_residual = set(frames["genai_risk_register.csv"]["residual_risk"]) - risk_levels
    if invalid_inherent or invalid_residual:
        raise ValueError("Risk register contains invalid risk ratings")

    for _, row in frames["control_effectiveness_score.csv"].iterrows():
        score = int(row["control_effectiveness_score"])
        if score < 0 or score > 100:
            raise ValueError(f"Control score out of range for {row['control_id']}")

    readme_path = ROOT / "README.md"
    if readme_path.exists():
        text = readme_path.read_text(encoding="utf-8").lower()
        found = [term for term in forbidden_readme_terms if term in text]
        if found:
            raise ValueError(f"README contains terms to avoid: {found}")

    print("Validation passed.")
    print(f"Use cases: {len(frames['genai_use_case_register.csv'])}")
    print(f"Prompt tests: {len(frames['prompt_test_cases.csv'])}")
    print(f"Tool call events: {len(frames['agent_tool_calls.csv'])}")
    print(f"PII tests: {len(frames['pii_leakage_tests.csv'])}")
    print(f"Hallucination evaluations: {len(frames['hallucination_eval_log.csv'])}")
    print(f"Guardrail tests: {len(frames['guardrail_test_results.csv'])}")
    print(f"Risk records: {len(frames['genai_risk_register.csv'])}")
    print(f"Controls: {len(frames['genai_control_library.csv'])}")
    print(f"Open findings: {(frames['red_team_findings.csv']['status'] != 'Closed').sum()}")

if __name__ == "__main__":
    main()
